### ISSUE TITLE
Feature request: search filenames

### ISSUE THREAD

**Issue by miketz** [dajva/rg.el#111]
Requesting a new feature.  The ability to search on filenames only, not file content.

Ripgrep can search filenames with this command:

    rg --files | rg SearchPattern

**Comment by dajva** [comment]
The package is not really setup to handle file name matches without specific content lines in the file. So would need some work to achieve.

**Comment by miketz** [comment]
OK. I'll close the request.  Sounds like the feature is out of scope.
