### ISSUE TITLE
rg.el not searching django.po files with "all"

### ISSUE THREAD

**Issue by jidicula** [dajva/rg.el#112]
Thanks for creating this package! It's a great wrapper around `ripgrep` and I use it many times every day. I lean heavily on this tool when trying to understand a new codebase, so it's been invaluable in my onboarding to new projects.

I'm trying to use `rg.el` to search the contents of `django.po` translation files in a particular project, but for some reason they're not being indexed when using the `all` file specifier. The peculiar thing is that I can search those files successfully when running `rg` from the shell, but not from this package. I don't have any flags enabled that would otherwise be filtering those files out, and those files are not in my `.gitignore` either.

Any ideas on what might be causing this?

**Comment by jidicula** [comment]
Update: I just tried setting `*.po` in the file specifier and I can search in those file now!

Is the behaviour of `all` to only work with a few specific filetypes (I notice a list of language choices when using tab to expand completion options) rather than indeed searching all files in the project?

**Comment by dajva** [comment]
The definition of *all* is to search all defined file types, both those internally defined in ripgrep binary and those you add in `rg-custom-type-aliases`. *everything* is what you would like to use for searching all files without considering defined aliases.

**Comment by jidicula** [comment]
Oh ok thanks!
