### ISSUE TITLE
Allow customizing content separator when not grouping results

### ISSUE THREAD

**Issue by joca-bt** [dajva/rg.el#114]
When grouping results (`(setq rg-group-result t)`) it's possible to change the content separator. When not grouping results there aren't as many customization options. Asking if it makes sense to have a `defcustom` to allow defining a custom content separator when not grouping results.

**Comment by dajva** [comment]
Not something I plan to support. Non grouped mode is essentially a legacy mode with less bells and whistles, mostly on par with what you would get in grep mode.
