### ISSUE TITLE
Search term not showing up in buffer name

### ISSUE THREAD

**Issue by b3n** [dajva/rg.el#118]
I see on the screenshot on `README.md` that the buffer is named `*rg require*`, where "require" was the search term. My buffer is always named `*rg*`. Is this a bug, or was there a different (i.e. non-default) configuration used for the screenshot?

**Comment by dajva** [comment]
This come from save search functionality. `rg-save-search-as-name` allows you to choose a name for the saved search buffer.
If you want this in general look into the [rg-buffer-name](https://rgel.readthedocs.io/en/2.0.3/configuration.html#option-rg-buffer-name) customization.

**Comment by b3n** [comment]
Thanks @dajva!
