### ISSUE TITLE
RG hangs when the search folder is too big

### ISSUE THREAD

**Issue by longitude** [dajva/rg.el#12]
When I search for a common word across a huge directory RG is causing EMACS to hang, RG buffer says compiling, is there a way we can cancel the search in progress.

**Comment by dajva** [comment]
You can use `kill-rg` but that needs a responding emacs so I assume that does not work in your case. Killing the `rg` subprocess from command line should work if emacs is non responsive.

**Comment by dajva** [comment]
I will close this as fixed by #17. Please reopen if you can still reproduce it.
