### ISSUE TITLE
Question: how to show hidden options in `rg-menu`

### ISSUE THREAD

**Issue by Aaronzinhoo** [dajva/rg.el#121]
I know this might be a simple question, but I wanted to make the [replace option](https://github.com/dajva/rg.el/blob/master/rg-menu.el#L149) show up in the transient map. I know the number next to the option is a priority level of some sort since I changed it to 3 and it popped up. I tried reading source code and could not find a variable to dictate whats shown. Any help is appreciated!

**Comment by dajva** [comment]
It's all documented in the transient docs. https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html#Enabling-and-Disabling-Suffixes
Essentially `C-x l` and then press the key(s) that trigger the option and select the level you want.

**Comment by Aaronzinhoo** [comment]
Thanks for that. I use magit but never realized transient's ability to update its menu! Thanks for the help!
