### ISSUE TITLE
In rg-dwim, opening the selected file will create a projectile first

### ISSUE THREAD

**Issue by e190** [dajva/rg.el#124]
In rg-dwim, opening the selected file will create a projectile first.This is troubling.
`
Projectile is initializing cache for /....../ ...
`
I remember the previous version didn't create pro first.I don't want this feature, I can only simply open the file..
I tried to find the function function triggered by pressing [RET] in rg-dwim, but could not find it.

**Comment by dajva** [comment]
This sounds like a projectile issue. This package should not do anything when jumping to the files in the result. Could for instance be `projectile-auto-update-cache` or similar.

**Comment by e190** [comment]
But I'm using Emacs-Q, testing rg-dwim alone without installing ile,
That's not going to happen

**Comment by dajva** [comment]
Can you invoke `rg-print-environment` and paste the result here?
You can also try to reproduce it in the dev env as described here: https://rgel.readthedocs.io/en/2.1.0/contribute.html#setup
There is no hard dependency on projectile in this package. If it's available it may be picked up though so it must be somewhere in your load path.

**Comment by dajva** [comment]
Maybe you did `apt install elpa-projectile` at some point?

**Comment by e190** [comment]
I do have projectile installed, and if I'm using rg, I disable projectile mode
That's not going to happen. This sounds like a projectile issue.
