### ISSUE TITLE
Default `--type`

### ISSUE THREAD

**Issue by winny-** [dajva/rg.el#131]
It appears `rg.el` suggests the `all` type out of the box.  This is a little different than what `rg` does on the command line.  It appears when `--type` isn't specified, `rg` on the command line will search all files (such as if one used no `--type`).

This caused a bit of confusion because if the file glob isn't defined in https://github.com/BurntSushi/ripgrep/blob/master/crates/ignore/src/default_types.rs , it's not considered by `rg.el` by default, unless you use the `everything` type.

Could it make more sense (and reduce user confusion), to change the default `type` to `everything`?

Example:  https://github.com/racket/racket/blob/master/racket/src/cs/rumble/parameter.ss has a file extension not defined in the default types known to ripgrep.  This means unless the user realizes that rg.el adds a new behavior in the form of the `everything` "type" (not a type to rg, but just a rg.el wrapper feature), they might not realize `all` does what they want and they want `everything` instead.

**Comment by dajva** [comment]
Thanks. It's configurable in [rg-default-alias-fallback](https://rgel.readthedocs.io/en/2.1.0/configuration.html#option-rg-default-alias-fallback). But sure, I think the default of that should possible be `everything` instead.
