### ISSUE TITLE
rg-isearch-menu should be autoloaded

### ISSUE THREAD

**Issue by hmelman** [dajva/rg.el#137]
`rg-isearch` recommends configuring it via:

```elisp
(define-key isearch-mode-map "\M-sr" 'rg-isearch-menu)
```
But this doesn't work alone, it fails on first use since `rg-isearch` isn't loaded. Putting an `;;;###autoload` token before the `transient-define-prefix` call I think will fix it, and not make the user do a `(require 'rg-isearch)` or their own `autoload` call.

**Comment by dajva** [comment]
Fixed. Thanks for the report.

**Comment by hmelman** [comment]
There's an extra space before the  `;;;###autoload` for `rg-isearch-menu` preventing it from working.
