### ISSUE TITLE
default-directory is not updated when using rg from an rg-mode buffer

### ISSUE THREAD

**Issue by classieur** [dajva/rg.el#139]
This is a regression from commit 82105c6ae75af1587884baeaf3668becd9eb5802.

Steps to reproduce:

- search for something in `/tmp/a`
- switch to buffer `*rg*`
- search for something in `/tmp/b` (with results)
- click on a result: file not found because `default-directory` is still set to `/tmp/a`

**Comment by dajva** [comment]
Thanks for the report. Silly mistake. Should work now.
