### ISSUE TITLE
*rg* buffer hangs when moderately long line is displayed

### ISSUE THREAD

**Issue by mbunkus** [dajva/rg.el#14]
I have a line in an elisp file that's currently 624 characters long (the list of packages to install from `init.el`). When such a line is found by rg-the-program, rg-the-Emacs-mode hangs each time that line is currently visible with 100% CPU. I have to press C-g repeatedly to get back movement, and if I do anything inside that buffer that doesn't scroll that long line offscreen with that action, Emacs will hang again.

What happens in detail:

* The `*messages*` buffer shows "rg finished (matches found)"
* The `*rg*` buffer is shown with the following content with the mode line saying somthing about "compiling":

```
-*- mode: rg; default-directory: "~/tmp/" -*-
rg started at Sun Aug  6 14:54:28

rg --color always --colors match:fg:red -n --type all --no-heading --type-add gn\:\*.gn --type-add gn\:\*.gni --type-add gyp\:\*.gyp --type-add gyp\:\*.gypi -i ack-and-a-half .
```

* When I press `C-g` repeatedly, I see messages such as `Error during redisplay: (jit-lock-function 259) signaled (quit)`
* After pressing them repeatedly, the full content of the `*rg*` buffer including the matched line is shown normally.

I've confirmed that I can reproduce it with `emacs -Q --eval '(package-initialize)'` followed by rg'ing for `ack-and-a-half` in a directory where the only file present is the following one:

```
    (rg rhtml-mode rinari bbdb-vcard ht gh mu4e-maildirs-extension erlang use-package magit magit-popup magit-svn magithub modern-cpp-font-lock dired-single w3m yasnippet yari yaml-mode test-simple systemd rustfmt rtm projectile poporg paredit nsis-mode nrepl nginx-mode markdown-mode magit-gh-pulls lua-mode ldap-mode json-mode iedit ido-completing-read+ hide-lines graphviz-dot-mode go-mode gist flymake-yaml flymake flycheck-rust find-things-fast f expand-region dockerfile-mode dash-functional csv-mode color-theme clojure-test-mode cargo browse-kill-ring+ bbcode-mode apache-mode alchemist ack-and-a-half)))
```

This looks similar to #12, but in my case the folder contains a single file, the file is under 1 KB in size, but the single line it contains is long.

Where the match occurs doesn't matter. For example, I can rg for "rhtml-mode" (which is the second entry in the line), and rg-the-mode hangs just the same.

rg-the-program finishes its search pretty much instantly when executing the command shown in the `*rg*` buffer on the command line.

**Comment by mbunkus** [comment]
I've played around with this a bit more. Shortening the line to e.g. 370 characters gives me a result (= the buffer is fully populated and control returned to Emacs) within four or five seconds. Adding just a couple of words here makes the time-to-return-of-control shoot through the root.

With such a shortened line I've run the profiler on rg-the-function. The result is this:

```
- command-execute                                                7941  94%
 - call-interactively                                            7941  94%
  - apply                                                        7941  94%
   - call-interactively@ido-cr+-record-current-command               7941  94%
    - apply                                                      7941  94%
     - #<subr call-interactively>                                7941  94%
      - funcall-interactively                                    7771  92%
       - execute-extended-command                                7771  92%
        - sit-for                                                7766  92%
         - read-event                                            7218  86%
          - redisplay_internal (C function)                      7212  86%
           - jit-lock-function                                   7212  86%
            - jit-lock-fontify-now                               7212  86%
             - jit-lock--run-functions                           7212  86%
              - run-hook-wrapped                                 7212  86%
               - #<compiled 0xc19ad9>                            7212  86%
                - font-lock-fontify-region                       7212  86%
                 - font-lock-default-fontify-region               7212  86%
                    font-lock-fontify-keywords-region               7212  86%
         + redisplay                                              548   6%
        + command-execute                                           5   0%
      + byte-code                                                 170   2%
+ ...                                                             421   5%
```

This leads me to believe that the regular expressions you're using make the regex engine do costly backtracking causing exponential increase in time with increase in input (line) length.

Commenting out the very last entry of `rg-mode-font-lock-keywords` (`("^\\(?:.+?-\\)*?[0-9]+-.*\n" (0 'rg-context-face))`) makes display instantaneous.

The problem is that the first non-capturing parenthesis can be repeated any number of times (the `*` after the parenthesis), but its content can be an arbitrary number of characters long — a typical disaster for regex engines. Removing the `*` seems to work fine performance-wise:

```lisp
("^\\(?:.+?-\\)?[0-9]+-.*\n" (0 'rg-context-face))
```

A quick test with `rg-command-line-flags` set to `'("-C" "1")` indicates the RE to work fine.

**Comment by dajva** [comment]
Thanks for your thorough investigation. I agree with your conclusion.

**Comment by mbunkus** [comment]
You're quite welcome! Thanks for providing such a useful mode in the first place.
