### ISSUE TITLE
Keep multiple search results' buffers

### ISSUE THREAD

**Issue by jjnilton** [dajva/rg.el#140]
I was wondering on how I could set it to keep previous search results' buffers instead of replacing with the new search, but I couldn't find that option.

The appropriate way would be to write a function that gives a unique name for the buffer?

Thanks for sharing this great package.

**Comment by dajva** [comment]
Should work now with the instructions in the doc.

**Comment by jjnilton** [comment]
Sorry, I missed this part in the docs. Thanks!
