### ISSUE TITLE
Would be nice if DWIM modes prompt for search string if no word at point

### ISSUE THREAD

**Issue by garyo** [dajva/rg.el#151]
I use the DWIM modes often. But I sometimes want to search for something in the current dir, but it's not the thing under point. This means I have to use the full `C-c s r`. It might be nice if there is nothing found under point in a DWIM mode, instead of returning "Empty string: no search done", prompt for something to search for. After all, "DWIM" is in the name. :-)
I know I can define a different custom search key, and I've done that, but for me at least it would be nice to just use the same `C-c s c` in both cases.

**Comment by dajva** [comment]
Agreed, seems useful. Thanks for the suggestion.

**Comment by dajva** [comment]
Implemented. Please try it out on master.

**Comment by garyo** [comment]
Works fine! Thx!
