### ISSUE TITLE
Question on searching and removing the whole line

### ISSUE THREAD

**Issue by djgoku** [dajva/rg.el#152]
if I search for `- value` and have it in a rg buffer how can I replace `\w+- value` with an empty line:

I have tried `[[:space:]]+- value` and `^\s-+- value` and replacing with ``, but that isn't working.

current file
```
test:
  - other
  - value
thing:
  - other
  - value
```
wanted:
```
test:
  - other

thing:
  - other

```

would be awesome if:

```
test:
  - other
thing:
  - other
```

https://emacs.stackexchange.com/a/45501

**Comment by dajva** [comment]
I suggest you try `M-x flush-lines`.
This is nothing provided by this package so more of a general emacs question so I will close this issue.
