### ISSUE TITLE
Comparison with Deadgrep?

### ISSUE THREAD

**Issue by defaultxr** [dajva/rg.el#157]
Hi. How does this package compare to [deadgrep](https://github.com/Wilfred/deadgrep)? Perhaps a feature comparison could be listed in the readme?

**Comment by dajva** [comment]
I wouldn't know TBH. Never tried that package. But my understanding is that it has simpler and more opinionated functionality and this package is more of a power tool. You have to take this statement with a grain of salt though, coming from me.
There is a comparison in deadgrep package https://github.com/Wilfred/deadgrep/blob/master/docs/ALTERNATIVES.md. It's not all that fair IMO, which what you can expect from a package manager writing about other packages.

So I would not do this myself but would possibly accept PR:s if those arise.
