### ISSUE TITLE
project.el issue

### ISSUE THREAD

**Issue by PyB1l** [dajva/rg.el#159]
Suddenly rg invocations started throwing 

`format: Wrong type argument: stringp, (Git "/project/path")
`

**Comment by dajva** [comment]
Can you provide more information, like the search you are trying to do. Would be really helpful if you post the output of `M-x rg-print-environment` also.

**Comment by DivineDominion** [comment]
I think this can be closed: With Emacs 29, IIRC, `project.el` changed the return value of `(project-current t)` from a path to a list or some such and the fix was to use `(project-root (project-current t))` to get the path from that list again.
