### ISSUE TITLE
Is there way to set default searching directory dynamically?

### ISSUE THREAD

**Issue by Insem** [dajva/rg.el#171]
Hello, I want to change default directory for rg outside of Emacs. I thought I can do it through rg-rerun-change-dir but it doesn't take arguments and set nil by default. Thanks

**Comment by dajva** [comment]
`(setq default-directory "/my/path")` with the `rg-result` buffer as the current?

**Comment by dajva** [comment]
Closing this. Please reopen if the issue persist.
