### ISSUE TITLE
would it  be possible to print number of matches found

### ISSUE THREAD

**Issue by longitude** [dajva/rg.el#18]
Instead of returning matches found. Is it possible to add number of matches found that will be really helpful.

<img width="421" alt="screen shot 2017-08-18 at 2 02 54 pm" src="https://user-images.githubusercontent.com/5510191/29471447-08c28eca-841e-11e7-92c5-8fc5c3323fcf.png">

**Comment by dajva** [comment]
It's possible but would need a setup of some compilation variables separate from `grep.el` that is currently used. So essentially, skip `grep-setup` and do our own implementation.
I am currently working on a feature that will count the matches anyway so if I get time I might do this as well. I'd like to move away from the `grep.el` dependencies eventually.

I don't have much time on this right now but would accpept a pr if you want to do it yourself.
