### ISSUE TITLE
Prioritized type aliases with built-in rg types

### ISSUE THREAD

**Issue by wavexx** [dajva/rg.el#180]
I'm frequently working on project that have mixed c/cpp files. More importantly, ".h" files are frequently cpp anyway. I believe this is pretty common. When I search, I obviously want to search both.

I'm using rg with a custom type: `--type:cxx:include:c,cpp` added to my RIPGREP_CONFIG_PATH., and `rg-ignore-ripgreprc` is set to nil so I can use this type on both cli and rg.el (I don't understand why one would want to ignore ripgreprg by default TBH, but anyway).

When I start a search with `rg-dwim` on a .h file, the `c` type is autodetected and used for search.
Adding `cxx` to `rg-prioritized-type-aliases` doesn't change anything.

However, if I add a custom alias named "0cxx" (so that it appears first in `rg --type-list`, this type is selected first and `rg-dwim` does what I mean™.

I expect `rg-prioritized-type-aliases` to work by probing for the specified list, and in order, before any remaining type in such case. My guess was that prioritized-type-aliases just re-ordered the type list by moving the specified list of types in front of the rest, but it doesn't seem to work like that.

**Comment by dajva** [comment]
>  don't understand why one would want to ignore ripgreprg by default TBH, but anyway
Well, use cases differs essentially and some flags may clash with what is used inside the pacakge.

> I'm using rg with a custom type: --type:cxx:include:c,cpp added to my RIPGREP_CONFIG_
I don't use ripgreprc myself so not sure how that works but shouldn't you be using `--type-add` to add a custom type?

**Comment by wavexx** [comment]
>I don't use ripgreprc myself so not sure how that works but shouldn't you be using --type-add to add a custom type?

I do. Typo on my part.

**Comment by dajva** [comment]
Ok, so exactly what syntax do you use in your `.ripgreprc`?
Using this file:
```bash
--type-add                   
cxx:include:c,cpp 
```
And then in emacs:
```elisp
(setq rg-prioritized-type-aliases '("cxx"))
(setq rg-builtin-type-aliases nil) ;; Clear cache
(setq rg-custom-type-aliases nil) ;; No distractions
(setenv "RIPGREP_CONFIG_PATH" "/home/david/.ripgreprc")
```
This makes it work for me so that I get the *cxx* type default selected when searching from `.h` files.

**Comment by wavexx** [comment]
Ok, so it looks like I was wrong overall. Setting `rg-prioritized-type-aliases` works as expected, but I never directly the cache while changing my rg/rg.el configuration while testing (I'm using emacsclient).

My `rg-custom-type-aliases` was already nil (and you also need `(setq rg-ignore-ripgreprc nil)` in the above of course). Now that I simply restarted the whole setup it works.

Maybe the fact that the internal type list is cached should be mentioned?

I only have one remaining question though: `rg-prioritized-type-aliases` says that "The order of the list is not significant.". But if I had two extra types and needed to prioritize between them, how would I do it?

**Comment by dajva** [comment]
Yeah, the cache could be better documented. It stems from the time where there was no `.ripgreprc` so outside changes were rare. 

>  But if I had two extra types and needed to prioritize between them, how would I do it?

Do you need to? There's only one type that can be selected for a specific file ending anyway. Perhaps I am missing something so could you describe a scenario where this would be useful?

**Comment by wavexx** [comment]
I have several types defined in ripgreprc I use via cli, depending on what I'm searching. Classic scenario for me is build systems, where cmake generates defines/flags which are then also used literally in python/c/cpp. This is usually also where lsp doesn't help any longer, so you need to switch to dumb search. In such cases, if search in cmake, I almost always want to include project sources to see where stuff is used.

```
--type-add cxx:include:c,cpp
--type-add allsources:include:c,cpp,py,cmake,sh
```

So the priority I'd like here is cxx, then allsources. So that when I'm on a c/cpp buffer, cxx is used (even though allsources does match), but allsources would actually be used in cmake instead.

**Comment by dajva** [comment]
Try the latest master now. I think this should work now

**Comment by wavexx** [comment]
Wasn't able to test before this was closed, but I confirm it works as expected.
