### ISSUE TITLE
Awesome Package

### ISSUE THREAD

**Issue by 1-9** [dajva/rg.el#2]
Thanks for this package, are there any plans to put this on Melpa? Also would you be able to add some details about how to install this package, I am new to emacs and found installation a bit tricky.

**Comment by dajva** [comment]
Thanks. I've considered putting it on melpa but I have never done it before so need to look into how it's done.

In the mean time, manual installation can be done by putting rg.el in your load path, usually under ~/.emacs.d and add `(require 'rg)` to your `init.el`. I'll add something to the readme file to clarify.

**Comment by dajva** [comment]
Fixed in commit 5893a2e58b7d5b76756679688124de728401fe9b

**Comment by dajva** [comment]
It's now available on [MELPA Stable](https://stable.melpa.org/#/rg) and [MELPA](http://melpa.org/#/rg)
