### ISSUE TITLE
how to move between results in *rg* buffer

### ISSUE THREAD

**Issue by nasoundead** [dajva/rg.el#24]
use "n"/"p" to move ? (I was using ag.el, and new to rg.el)

**Comment by dajva** [comment]
`rg-mode` inherits from `compilation-mode` so you can use the key bindings in compilation mode for navigation. `C-h m`gives you a description of the mode and all available key bindings.
`n` and `p` navigates results and shows the file in another buffer. If you just want to jump in the result buffer you can use `M-n` and `M-p`.

**Comment by nasoundead** [comment]
OK.
