### ISSUE TITLE
Evaluating autoloads source requires byte-compiled rg.elc or byte-compiled autoloads with requiring rg.elc

### ISSUE THREAD

**Issue by yewton** [dajva/rg.el#29]
Otherwise it raises `(void-function rg-search-parse-body)`

Since https://github.com/dajva/rg.el/commit/2a3e6acafb8e1a598b1c744ba57647d93d2761e3

**Comment by yewton** [comment]
Related post: https://www.reddit.com/r/emacs/comments/63u5yn/how_to_use_autoload_cookies_for_custom_defunlike/

**Comment by dajva** [comment]
Thanks for the report

**Comment by yewton** [comment]
I confirmed! Thanks! 😄
