### ISSUE TITLE
rg does not support wgrep when rg-results-group option is enabled.

### ISSUE THREAD

**Issue by stardiviner** [dajva/rg.el#34]
RT

**Comment by dajva** [comment]
Works for me on latest master. Did you follow the instructions in the README?
You need to install `wgrep-ag` and add this to the configuration:
```
(add-hook 'rg-mode-hook 'wgrep-ag-setup)
```

**Comment by stardiviner** [comment]
I did have this configuration, but I found I use `use-package` and have not realized `wgrep-ag` is a package, so I have not `:ensure wgrep-ag`. After added that. It works now. Thanks.
