### ISSUE TITLE
Rg always asks for which file type to search.

### ISSUE THREAD

**Issue by pranavsharma** [dajva/rg.el#45]
Can this be defaulted to --type all ? It's a bit annoying to always type 'all' when presented with a prompt "Search for files"..

**Comment by dajva** [comment]
Yes you can define your own search function with the
`rg-define-search` macro like so:
```
(rg-define-search rg-search-all
:files "all")
```
And bind it to your favorite key behind the `rg-keymap-prefix`.
```
(define-key rg-global-map "a" 'rg-search-all)
```
There are a lot of more options for the `rg-define-search` macro if you want to tune it more specifically.

**Comment by dajva** [comment]
I close this now. Please reopen if your issues are not resolved.

**Comment by pranavsharma** [comment]
I use rg-project. Does rg-define-search work for project searches as well?

**Comment by pranavsharma** [comment]
I tried this and it works. Thanks!

`(rg-define-search rg-search-all :files "all" :dir project)`
