### ISSUE TITLE
--glob overrides any other ignore logic

### ISSUE THREAD

**Issue by muffinmad** [dajva/rg.el#46]
Hi!

I used ```*``` for ```Search in files``` to search in all but ignored files.

After https://github.com/dajva/rg.el/commit/dafd9e7b44e26de8ee022e7626d47495c05c13ea rg doesn't respect my ignore rules because, according to rg man, ```--glob``` option always overrides any other ignore logic.

I've tried create custom type alias like this:
```
(custom-set-variables
 '(rg-custom-type-aliases '(("not_ignored" . "*"))))
```
but searching using this type alias gives error:
```
/usr/local/bin/rg --color always --colors match:fg:red -n --type-add not_ignored\:\* --context 2 --follow -i --heading --column --type not_ignored -e foo
invalid definition (format is type:glob, e.g., html:*.html)
```

How can i search in all but ignored files?

**Comment by dajva** [comment]
Oh, that was an unintentional change. I guess I was to eager to get rid fo that internal "custom" type. I will revert https://github.com/dajva/rg.el/commit/dafd9e7b44e26de8ee022e7626d47495c05c13ea.

Thanks for the report. That was really fast!

**Comment by dajva** [comment]
BTW, the problem with your custom alias is the underscore which isn't allowed in type aliases by the rg binary.
