### ISSUE TITLE
make the default default match type configurable

### ISSUE THREAD

**Issue by slippycheeze** [dajva/rg.el#48]
I'd prefer the default to be "everything" rather than "all" file types when I search, and there is no more specific default available.  Unfortunately, that is hard-coded into the `rg-default-alias` method right now, so I have to do horrible things like edit the package code, or advise it, to get that.

A simple configurable option would probably work equally well in context, and would make this vastly more accessible.

**Comment by dajva** [comment]
Sure, sounds good.

**Comment by dajva** [comment]
Implemented now. Please try it out.
