### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by seagle0128** [dajva/rg.el#56]
Thanks for this amazing tool! I love it.

Can you add an empty line after the command line? It's annoying to combine commd line and results together. Thank you so much!

![image](https://user-images.githubusercontent.com/140797/55464380-954ed780-562d-11e9-9e0b-e0ce2bbf250b.png)

**Comment by dajva** [comment]
Try now.

**Comment by seagle0128** [comment]
Thank you so much, for the quick fixing!
