### ISSUE TITLE
I want no roll in rg-dwim

### ISSUE THREAD

**Issue by e190** [dajva/rg.el#63]
I want current position what is always top in rg-dwim.What should I do?

**Comment by dajva** [comment]
Sorry, I don't understand this question. Can you describe in more detail what you are trying to do and how actual result differ from the expected result

**Comment by e190** [comment]
During the search, the number of items searched continues to increase, so keep scrolling down.
I want the dwim window to stop scrolling and stay on top.
Do you know what I mean?

**Comment by dajva** [comment]
Ah, ok. I guess that happens in all the `rg-*` functions, right?
This package is based on compilation-mode so I suspect it might be that `compilation-scroll-output` is `t` and need to be changed to `nil` in your init.

**Comment by e190** [comment]
Yes - that's it! Thank you.
