### ISSUE TITLE
wgrep no longer working

### ISSUE THREAD

**Issue by andschwa** [dajva/rg.el#66]
Hi,

I am using commit 036675f64 of rg.el with wgrep.el version 2.3.0, and I cannot apply my changes.

I can successfully enter wgrep mode, make my changes, and then execute `wgrep-finish-edit`, but all that happens is I hit this part of wgrep: https://github.com/mhayashi1120/Emacs-wgrep/blob/379afd89ebd76f63842c8589127d66096a8bb595/wgrep.el#L1012

With the error message:

> There are 3 unapplied changes. (0 changed)

😢

**Comment by dajva** [comment]
Thanks for the report. I think 2648335 is the problem. See if I can find out what's the problem.

**Comment by dajva** [comment]
I think this should work now. Please try it out and report back if it's still broken in some way.

**Comment by andschwa** [comment]
It's working now, thank you so much!
