### ISSUE TITLE
How to focuses rg search buffer when finaily search

### ISSUE THREAD

**Issue by taigacute** [dajva/rg.el#75]
when i used the `rg-dwim-project-dir`,i want focuses the buffer `*rg*` ,now when searched , i also on current widnow.

**Comment by dajva** [comment]
Maybe add this? `(add-hook 'rg-mode-hook (lambda () (switch-to-buffer (current-buffer))))`

**Comment by taigacute** [comment]
no . when use command it will generate a buffer *rg* on split . so i want focuses in but keep the file buffer.
![image](https://user-images.githubusercontent.com/41671631/75673175-4b4af780-5cbd-11ea-9e1e-eb5f60f3e1ff.png)

**Comment by dajva** [comment]
Then you can use `switch-to-buffer-other-window` instead of `switch-to-buffer`.

**Comment by taigacute** [comment]
@dajva  it works well .thanks.
