### ISSUE TITLE
Is there a way to not prompt for file type all the time?

### ISSUE THREAD

**Issue by garyo** [dajva/rg.el#77]
I almost always want to search all (non-ignored) files. Is there an `rg` command to skip the file-type prompt and use a default set?

**Comment by dajva** [comment]
You can create your own search frontend with `rg-define-search`:
```elisp
(rg-define-search rg-everything
  "Search everything."
  :files "everything"
  :confirm prefix
  :menu ("Search" "e" "Everything")
```
See https://rgel.readthedocs.io/en/latest/configuration.html#function-rg-define-search and https://rgel.readthedocs.io/en/latest/usage.html#file-type-aliases for more info.

**Comment by jvillasante** [comment]
But if I want to use `rg-menu` as opposed to my own custom search, how can I set some defaults? like `--hiden`, `:files "everything"`, etc...

**Comment by dajva** [comment]
The `:menu` key of `rg-define-search` will add your search to the menu. For setting defaults in the menu, see transient manual: https://www.gnu.org/software/emacs/manual/html_mono/transient.html#Usage
