### ISSUE TITLE
Disable `Global key bindings for `rg' enabled with prefix: ` message in `rg-enable-default-bindings`

### ISSUE THREAD

**Issue by michaelmhoffman** [dajva/rg.el#83]
Feature request: could you disable this message? If it's part of one's `init.el`, it gets added to a lot of noise at Emacs initialization. Most packages that install keybindings don't report such a message in my experience.

Thanks for this useful package!

**Comment by dajva** [comment]
Yeah, you are right. It could be removed.

**Comment by michaelmhoffman** [comment]
Thanks for fixing this! Do you think you could push it to the `stable` branch so it goes into the MELPA Stable version?
