### ISSUE TITLE
Highlighting Lines

### ISSUE THREAD

**Issue by wusticality** [dajva/rg.el#93]
This package is a lifesaver. :)

When navigating the results buffer with `n` / `p` and highlighting matching lines, is it possible to somehow highlight the *entire* line and keep the line highlighted? Currently the highlight disappears after a second or so and only covers part of the line.

Thanks!

**Comment by dajva** [comment]
This is controlled by the emacs `next-error` framework in combination with `compilation-mode`.
You can set it to use a fringe arrow or "permanent" highlighting instead of match highlight but I have not seen anything for highlighting full line (emacs 26).
```elisp
(defcustom next-error-highlight-no-select 0.5
  "Highlighting of locations in `next-error-no-select'.
If number, highlight the locus in `next-error' face for given time in seconds.
If t, highlight the locus indefinitely until some other locus replaces it.
If nil, don't highlight the locus in the source buffer.
If `fringe-arrow', indicate the locus by the fringe arrow
indefinitely until some other locus replaces it."
  :type '(choice (number :tag "Highlight for specified time")
                 (const :tag "Semipermanent highlighting" t)
                 (const :tag "No highlighting" nil)
                 (const :tag "Fringe arrow" fringe-arrow))
  :group 'next-error
  :version "22.1")
```

**Comment by dajva** [comment]
Closing this since it not much to do from this package with the current architecture.

**Comment by wusticality** [comment]
Ok, thanks!
