### ISSUE TITLE
Compilation mode filter hook called on partial lines

### ISSUE THREAD

**Issue by egorenar** [dajva/rg.el#95]
Sometimes, the rg-filter hook is called and the last line is incomplete, the last line of the region passed to the hook ends in the middle of the ANSI escape sequence and this breaks the output. Any idea how to fix it ? Because the current handling of this case just deletes the last incomplete ANSI sequence and this breaks everything that follows.

![Untitled](https://user-images.githubusercontent.com/22225998/90927227-f7f86d00-e3f4-11ea-983e-440df4840ed5.png)

**Comment by dajva** [comment]
Good that you found the source of the problem.
