### ISSUE TITLE
rg-enable-default-bindings

### ISSUE THREAD

**Issue by sjLambda** [dajva/rg.el#96]
Where are the default bindings? I looked in the info file and the usual places. I found the old bindings in rg.el, but not the new.

**Comment by dajva** [comment]
If you are referring to the bindings enabled by `rg-enable-default-bindings`, they are here: https://github.com/dajva/rg.el/blob/4dac7ab60a7b30707aa15cc345c07804dead44ca/rg.el#L162
The default behavior for `rg-enable-default-bindings` is the `rg-menu` these days and there are all bindings explicit in the menu.
The bindings for the results buffer is here: https://github.com/dajva/rg.el/blob/4dac7ab60a7b30707aa15cc345c07804dead44ca/rg-result.el#L242
Can easiest be found by pressing `C-h m` in the results buffer.
