### ISSUE TITLE
respect compilation-scroll-output

### ISSUE THREAD

**Issue by jixiuf** [dajva/rg.el#97]
```
 (setq compilation-scroll-output 'first-error)
```

When I set  `compilation-scroll-output`  to `t` or `nil`, rg respect this variable,
But when I set I tot `first-error`, it doesn't .

**Comment by dajva** [comment]
Did you modify `rg-group-result` setting?
This is a known issue in the regexps when `rg-group-result` set to `nil`. There is also a bug that these regexps are used in grouped mode. The latter can easily be fixed but wont help if you are not using grouped results mode (which is the default).

**Comment by jixiuf** [comment]
yes 
```
 (setq rg-group-result nil)
```

**Comment by dajva** [comment]
Unfortunate. Ok so the regexp is matching the line `rg started at Sat Sep 26 12:00:00` line. I think you can see that the caret jumps there. That would actually be a possible match line with file name "rg started at Sat Sep 26 12" and line, column as both "00"
I think grep-mode has some clever stuff in its error matching regexp that could be used to filter out valid but weird enough file names to avoid that match. I'll see what I can find.

**Comment by dajva** [comment]
This actually looks to be an upstream bug in `compilation-mode`.
Reported a bug to see if emacs maintainers agree: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43651

**Comment by dajva** [comment]
Upstream bug has been fixed. I guess you have to wait until emacs 28 to get it though, unless you want to fork compile.el and backport the fix to your current emacs.
